### ISSUE TITLE
Add config option for rejecting keysends

### ISSUE THREAD

**Issue by valentinewallace** [rust-bitcoin/rust-lightning#1017]
As pointed out by @ariard here: https://github.com/rust-bitcoin/rust-lightning/pull/967#pullrequestreview-713261889

**Comment by TheBlueMatt** [comment]
This was discussed briefly at the meeting this week. I'm a little dubious of the value of this - because we check the preimage matches before generating the `PaymentReceived` I'm not sure there's a lot to worry about regarding strange privacy-breaking attacks here, and users can trivially just "reject" manually by handling the events.

**Comment by valentinewallace** [comment]
Ah, right. At least this issue documents the thought process. Closing.

**Comment by valentinewallace** [comment]
Although -- likely not a concern in practice, but if a user were to prefer to always reject keysends, it might be better if they didn't advertise the version bit for it

**Comment by TheBlueMatt** [comment]
True, I suppose we could use the config to unset the feature bit. I'm open to that, I guess, I don't feel strongly, though.
