### ISSUE TITLE
Implement a Config interface

### ISSUE THREAD

**Issue by ariard** [rust-bitcoin/rust-lightning#128]
Was thinking of the new TODO in `channel` about optional additional constraints, the user should be able to configure them easily if not opting for default policy. So need a Config interface we can pass everywhere, with a lock, and that can be updated on-fly

**Comment by TheBlueMatt** [comment]
At least for just those I figure we dont need anything so heavy-weight. For inbound channels we likely dont care much about any of those, as long as our routing stuff is updated to handle it appropriately, for outbound channels, the user may have some expectation of channel features, but just passing in an Option<>al struct when creating a channel seems sufficient to me, no? Why have some on-the-fly updated locked datastructure?

**Comment by ariard** [comment]
I had in head a general config, not only the channel one. Just an Option<> struct as you said should be fine. Maybe you want the user to be able to change the config after start, without launching again the lightning daemon process.

**Comment by TheBlueMatt** [comment]
I'm not sure what the use-case is for changing config at runtime, especially since most things you might want to change (eg proportional feerate) may require channel_updates to go out. Depends on exactly what gets included, I guess, but probably best to avoid jumping down the rabit hole of complication until we have a better picture of what all we might want to be user-configurable.

**Comment by ariard** [comment]
I think #234 is good enough for this one? I'm closing but feel free to reopen it!
