### ISSUE TITLE
Check commitment transaction fee when receiving update_fee

### ISSUE THREAD

**Issue by yuntai** [rust-bitcoin/rust-lightning#204]
Follow up on #187 and #200.

Implement this from the spec
> if the sender cannot afford the new fee rate on the receiving node's current commitment transaction:
SHOULD fail the channel,
but MAY delay this check until the update_fee is committed.

**Comment by TheBlueMatt** [comment]
Merged #231 but realized after merge that it doesn't actually check including subtracting the HTLC outputs (ie that the remote needs to be able to afford to create their to_self output, not just afford to_self + pending htlcs. In any case, we can just punt on this for now I think since spec 1.1 should get rid of update_fee wholesale.

**Comment by TheBlueMatt** [comment]
Closing hoping we get option_simplified_commitment (#365).
