### ISSUE TITLE
Run tests in WASM

### ISSUE THREAD

**Issue by TheBlueMatt** [rust-bitcoin/rust-lightning#354]
Thanks to @elichai we're almost good to go running in WASM (though are waiting on upstream project releases). We should get travis testing this to make sure we dont regress after we are ready.

**Comment by elichai** [comment]
Glad to help,
I'm fulled with other work right now but quick helpful links to add full travis support for this are:
https://github.com/elichai/rust-lightning/tree/wasm/wasm-test
https://github.com/rustwasm/wasm-pack-template/blob/master/.travis.yml
(we need to actually run stuff, because the fact that it compiles says basically nothing)

But basically we should use https://rustwasm.github.io/wasm-pack/book/commands/test.html

**Comment by elichai** [comment]
This should provide the needed upstream changes: https://github.com/rust-bitcoin/rust-bitcoin/pull/298

**Comment by TheBlueMatt** [comment]
This should ultimately end up a part of https://github.com/lightningdevkit/ldk-garbagecollected, especially post-no_std.
