### ISSUE TITLE
Cannot open channel from lnd to rust-lightning - Peer's feerate much too high

### ISSUE THREAD

**Issue by yaslama** [rust-bitcoin/rust-lightning#464]
I compiled and ran the sample app from https://github.com/TheBlueMatt/rust-lightning-bitcoinrpc.
Then I tried to open a channel from lnd to rust-lightning using the command:
`lncli openchannel --node_key <rust-lightning-pubkey> --local_amt 1000000`.
I received the error in lnd:
`Peer's feerate much too high`
I saw the same error in rust-lighnting:
```
ERROR [lightning::ln::channelmanager : /path/rust-lightning/lightning/src/ln/channelmanager.rs, 2680] Peer's feerate much too high
TRACE [lightning::ln::peer_handler : /path/rust-lightning/lightning/src/ln/peer_handler.rs, 1052] Handling SendErrorMessage HandleError event in peer_handler for node <nodeid> with message Peer's feerate much too high
```

**Comment by TheBlueMatt** [comment]
There's one of a few things going on:
 * Its possible you just started your testnet node and it doesn't have good fee estimates yet, but the lnd you're peering with does (or at leas, it thinks it does, but probably doesn't, cause anything other than min-fee on testnet is bogus),
 * its a bug in lnd where it over-assumes feerates due to some peculiarities on testnet.

The easy fix is probably just to edit the sample client to adjust the HighPriority fee upwards, which I went ahead and did here: https://github.com/TheBlueMatt/rust-lightning-bitcoinrpc/commit/53ea8f26c66fc41f0bad12659f7a8bc8f73e5526 let me know if that doesn't work.

**Comment by yaslama** [comment]
Thanks @TheBlueMatt but the master branch of TheBlueMatt/rust-lightning-bitcoinrpc doesn't compile.
But I made the same change using the commit e78c8c1620fba921ce1c5094ce4281dae1546f7e and it works when I increased the factor (10 was not sufficient). But now, I obtain the error:
`Peer tried to open channel but their announcement preference is different from ours`

**Comment by TheBlueMatt** [comment]
Oops, I think I pushed it against my master to pick up some in-review features and fixes, but it may have been broken, sorry about that. The error you see is due to the config setting in the sample app - we set whether we want announced channels based on [this constant](https://github.com/TheBlueMatt/rust-lightning-bitcoinrpc/blob/master/src/main.rs#L73), which sets [announced_channel](https://docs.rs/lightning/0.0.10/lightning/util/config/struct.ChannelConfig.html#structfield.announced_channel) in the config, [who's setting is, by default, enforced to match for inbound channels or we will reject it](https://docs.rs/lightning/0.0.10/lightning/util/config/struct.ChannelHandshakeLimits.html#structfield.force_announced_channel_preference).

**Comment by yaslama** [comment]
I pulled the last master but I still have compilation errors [I am using cargo 1.40.0 (bc8e4c8be 2019-11-22) and rustc 1.40.0 (73528e339 2019-12-16)]. As soon as it compiles, I'll try to open a private channel from lnd.

```
$ ~/.cargo/bin/cargo build
   Compiling rust-lightning-bitcoinrpc v0.0.1 (path/rust-lightning-bitcoinrpc)
error[E0027]: pattern does not mention field `payment_secret`
   --> src/main.rs:141:6
    |
141 |                     Event::PaymentReceived { payment_hash, amt } => {
    |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing field `payment_secret`

error[E0061]: this function takes 3 parameters but 2 parameters were supplied
   --> src/main.rs:144:30
    |
144 |                             if us.channel_manager.claim_funds(payment_preimage.clone(), amt) { // Cheating by using amt here!
    |                                                   ^^^^^^^^^^^ expected 3 parameters

error[E0061]: this function takes 2 parameters but 1 parameter was supplied
   --> src/main.rs:150:27
    |
150 |                             us.channel_manager.fail_htlc_backwards(&payment_hash);
    |                                                ^^^^^^^^^^^^^^^^^^^ expected 2 parameters

error: aborting due to 3 previous errors

Some errors have detailed explanations: E0027, E0061.
For more information about an error, try `rustc --explain E0027`.
error: could not compile `rust-lightning-bitcoinrpc`.

To learn more, run the command again with --verbose.
```

**Comment by TheBlueMatt** [comment]
Grrr lol, I had another commit that was only partially done so hadn't pushed and forgot it updated to the new API...I pushed it anyway so you can move forward.

**Comment by yaslama** [comment]
Thanks @TheBlueMatt . It compiles now. I am closing the issue.
