### ISSUE TITLE
Peer_handler: disable peer  encryption (BOLT8)

### ISSUE THREAD

**Issue by ariard** [rust-bitcoin/rust-lightning#480]
BOLT8 encryption should be an option, meshnet people are interested @willcl-ark

**Comment by TheBlueMatt** [comment]
Hmm, I dont think this should live in the peer_handler. If you just implement https://docs.rs/lightning/0.0.10/lightning/util/events/trait.MessageSendEventsProvider.html you can handle the messages any way you'd like (though we need to expose their innards), I presume the mesh folks will want to so do anyway since the underlying may not be TCP/IP at all anyway.

Closing as ENOTABUG, though we should open something to track exposing message innards.
