### ISSUE TITLE
Spontaneous/keysend payments

### ISSUE THREAD

**Issue by valentinewallace** [rust-bitcoin/rust-lightning#505]
Current plan is to match lnd's implementation, so basically (IIUC):

- if sending a keysend payment:
  -  set a custom TLV record (type 5482373484) in the `update_add_htlc` message with the value being the payer's desired preimage (the payment hash should also be set accordingly)
- if receiving a keysend payment:
  - detect the custom TLV record as signalling the payment to be a keysend payment
  - just-in-time generate an invoice corresponding to the payer's desired preimage, so it's as if the payer is paying an invoice that already existed
- enable users to refuse to accept keysend payments

**Comment by TheBlueMatt** [comment]
We should definitely write up a BOLT PR for whatever we do - shipping spontaneous payments without a spec is pretty gross from a UX perspective - suddenly you don't just need a lightning wallet to pay people you need a lightning wallet with specific features to pay someone, which is, like, the worst UX you could come up with.

**Comment by valentinewallace** [comment]
> shipping spontaneous payments without a spec is pretty gross from a UX perspective

Ah, I take this to mean we won't be merging any custom TLV for it, but instead wait for a spec update before merging into RL?

**Comment by TheBlueMatt** [comment]
Never is a strong word, I'm just noting that fragmenting the sending UX so that users can't even get by with "you have a lightning wallet? good I can send you money" to now be "you have a lightning wallet? wait, does it support X feature? oh, that's not in the UI, hmm, let me google for it, one minute..." is, like, absolutely hilariously horrible. If it seems like kinda everyone is moving towards something we can run with it no problem, but there should at east be effort to standardize.
