### ISSUE TITLE
Possibly incorrect channel reserve referenced when updating feerate_per_kw

### ISSUE THREAD

**Issue by valentinewallace** [rust-bitcoin/rust-lightning#612]
Referencing this line: https://github.com/rust-bitcoin/rust-lightning/blob/9098240e341cf09578819cdf1d2950303478b137/lightning/src/ln/channel.rs#L1850

I believe instead of `self.their_channel_reserve`, it should be `self.get_our_channel_reserve()` (because we're checking if the remote is going below _their_ channel reserve (required by us) by updating the fee).

Lmk if I've misunderstood. Related to #181.

**Comment by TheBlueMatt** [comment]
Yep! That's definitely wrong. In general our `update_fee` codepaths are super under-tested and under-reviewed, mostly because I'd rather remove them then bother testing them (lightning `update_fee` is kinda a bogus concept that exists as a stop-gap to anchor outputs, so I'm dubious of spending too much effort trying to get it exactly right, especially when its doubly hard to get right compared to the rest of the state machine).

**Comment by TheBlueMatt** [comment]
Closed by #613.
